InformationFile/Controllers/WorkUserController.cs
using InformationFile.Extention;
using InformationFile.Models.Work;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InformationFile.Controllers
{
    public class WorkUserController : Controller
    {
        private TimaFMEntities db = new TimaFMEntities();
        // GET: WorkUser
        [CheckLogin]
        public ActionResult Index(WorkModel model)
        {
            ViewBag.UserName  = AuthenUser.CurrentUser().Fullname;
            var userid = AuthenUser.CurrentUser().UserID;


            model.CurrentPage = model.CurrentPage == 0 ? 1 : model.CurrentPage;
            //var lstwork = db.tblWorkUsers.Where(m => m.ToUser == userid).ToList();
            //var total = lstwork.Count();

            //lstwork.Skip((model.CurrentPage - 1) * 10).Take(10).ToList();
            //model.ListItem = lstwork.Select(m => new WorkItemModel()
            //{
            //    WorkId = m.WorkId,
            //    Description = db.tblWorks.FirstOrDefault(l=>l.WorkId==m.WorkId).Description,
            //    WorkName = db.tblWorks.FirstOrDefault(l => l.WorkId == m.WorkId).WorkName,
            //    MediaUrl = db.tblWorks.FirstOrDefault(l => l.WorkId == m.WorkId).MediaUrl,
            //    Createdate = db.tblWorks.FirstOrDefault(l => l.WorkId == m.WorkId).Createdate ,
            //    ResourceName = db.tblWorks.FirstOrDefault(l => l.WorkId == m.WorkId).MediaUrl,
            //    FromUser = db.tblUsers.FirstOrDefault(n => n.UserID == m.UserID).Fullname,
            //    Status = (int)m.Status
            //    //Url = "/DATA" + resource.FirstOrDefault(k => k.ResourceID == m.ResourceID).ResourceUrl + "/" + m.MediaUrl

            //}).ToList();

            var lstWorkUser = (from workUser in db.tblWorkUsers
                     join work in db.tblWorks on workUser.WorkId equals work.WorkId
                     join resources in db.tblResources on work.ResourceID equals resources.ResourceID
                     where workUser.ToUser == userid
                     select new {
                         WorkId = workUser.WorkId ,
                         WorkName = work.WorkName,
                         Description = work.Description,
                         MediaUrl = work.MediaUrl,
                         Createdate = work.Createdate,
                         ResourceName = resources.Description,
                         ResourceID = work.ResourceID,
                         UserID = work.UserID,
                         Status = work.Status,
                         NoteByLeader = work.NoteByLeader
                     }).ToList();
            var total = lstWorkUser.Count();
            lstWorkUser.OrderByDescending(k => k.Createdate).Skip((model.CurrentPage - 1) * 10).Take(10).ToList();

            model.ListItem = lstWorkUser.Select(m => new WorkItemModel()
            {
                WorkId = m.WorkId,
                Description = m.Description,
                WorkName = m.WorkName,
                MediaUrl = m.MediaUrl,
                Createdate = m.Createdate,
                ResourceName = m.ResourceName,
                ResourceID = (int)m.ResourceID,
                FromUser = db.tblUsers.FirstOrDefault(l=>l.UserID ==m.UserID).Fullname,
                Status = (int)m.Status,
                NoteByLeader = m.NoteByLeader

                //MediaUrl = "/DATA" + db.tblResources.FirstOrDefault(k => k.ResourceID == m.ResourceID).ResourceUrl + "/" + m.MediaUrl

            }).ToList();
            ViewBag.CurrentPage = model.CurrentPage;
            ViewBag.TotalPage = (int)Math.Ceiling((decimal)total / 10);

            return View(model);
        }

        public ActionResult UpdateStatusWork(int workId, string notebyuser,int status)
        {
            try
            {
                var userid = AuthenUser.CurrentUser().UserID;

                tblWork wk = new tblWork();
                wk = db.tblWorks.Find(workId);
                db.Entry(wk).State = EntityState.Modified;
                wk.NoteByUser = notebyuser;
                if (status ==1)
                {
                    wk.Status = StatusEnum.HoanThanh.GetHashCode();
                    SendMailSuccessWork(workId);
                }
                else
                {
                    wk.Status = StatusEnum.DangXuLy.GetHashCode();
                }
                wk.DoneByUser = userid;
                db.SaveChanges();
                db.Dispose();
                return new JsonResult { Data = new { Status = 1, Message = "Cập nhật công việc thành công" } };
            }
            catch (Exception e)
            {
                ////var a = e.Message;
                return new JsonResult { Data = new { Status = 0, Message = "Lỗi .! Cập nhật công việc  thất bại" } };
            }
        }
        [CheckLogin]
        [HttpPost]
        public JsonResult ExporFile(int id )
        {
            string fileName = "";
            if (id > 0)
            {
                IQueryable<tblWork> work = db.tblWorks;
                fileName = work.FirstOrDefault(m => m.WorkId == id).MediaUrl;
                db.Dispose();
                return Json(new { fileName = fileName, errorMessage = "" });
            }
            else
            {
                return Json(new { fileName = fileName, errorMessage = "Không tìm thấy file" });
            }

        }
        [CheckLogin]
        [HttpGet]
        public ActionResult Download(string file, int resourceID)
        {
            //get the temp folder and file path in server
            IQueryable<tblResource> resource = db.tblResources;
            var resourceUrl = resource.FirstOrDefault(k => k.ResourceID == resourceID).ResourceUrl;
            var path = "~/Data" + resourceUrl;
            db.Dispose();

            string fullPath = Path.Combine(Server.MapPath(path), file);

            //return the file for download, this is an Excel 
            //so I set the file content type to "application/vnd.ms-excel"
            return File(fullPath, "application/vnd.ms-excel", file);
        }

        public void SendMailSuccessWork(int workID)
        {
            var userid = AuthenUser.CurrentUser().UserID;
            var work = db.tblWorks.FirstOrDefault(m => m.WorkId == workID);
            if (work.AssignByUser > 0 )
            {
                var user = db.tblUsers.FirstOrDefault(n => n.UserID == work.AssignByUser);
                var subject = "Hoàn thành công việc" + work.WorkName;
                SendMailTima.SendEmail(user.Email, subject, work.Description);
            }

        }
    }
}

InformationFile/Views/WorkUser/Index.cshtml
@model InformationFile.Models.Work.WorkModel
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="#">Đầu việc được giao </a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>@ViewBag.UserName</span>
        </li>
    </ul>
</div>
<br />
<div class="portlet-title">
    <div class="tools">
        <a href="javascript:;" class="collapse"> </a>
        <a href="#portlet-config" data-toggle="modal" class="config"> </a>
        <a href="javascript:;" class="reload"> </a>
        <a href="javascript:;" class="remove"> </a>
    </div>
</div>
<input type="hidden" value="1" name="PageCurrent" id="PageCurrent" />
<div class="portlet-body form">
    <!-- BEGIN FORM-->
    <div class="form-horizontal">
        <div class="clearfix"></div>
        <table class="table table-striped table-bordered table-hover table-header-fixed dataTable no-footer" id="sample_1" role="grid" aria-describedby="sample_1_info">
            <thead>
                <tr>
                    <th> # </th>
                    <th class="text-center"> Đầu việc </th>
                    <th class="text-center"> Mô tả </th>
                    <th class="text-center"> Từ phòng ban</th>
                    <th class="text-center"> Người tạo</th>
                    <th class="text-center"> Ngày tạo </th>
                    <th class="text-center"> Trưởng phòng note </th>
                    <th class="text-center">Trạng thái</th>
                    <th class="text-center"> Download File </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.ListItem != null && Model.ListItem.Count > 0)
                {
                    int indexRow = 0;

                    if (Model.CurrentPage > 1)
                    {
                        indexRow = 10 * (Model.CurrentPage - 1);
                    }
                    foreach (var item in Model.ListItem)
                    {
                        indexRow++;
                        <tr>
                            <td> @indexRow </td>
                            <td class="text-center"> @item.WorkName </td>
                            <td class="text-center"> @item.Description </td>
                            <td class="text-center"> @item.ResourceName </td>
                            <td class="text-center"> @item.FromUser </td>
                            <td class="text-center"> @item.Createdate.GetValueOrDefault().ToString("dd/MM/yyyy HH:mm")</td>
                            <td class="text-center"> @item.NoteByLeader </td>
                            @if (item.Status == InformationFile.Extention.StatusEnum.HoanThanh.GetHashCode())
                            {
                                <td class="text-center text-success"> @item.StatusView </td>
                            }
                            else if (item.Status == InformationFile.Extention.StatusEnum.DangXuLy.GetHashCode())
                            {
                                <td class="text-center text-danger"> @item.StatusView </td>
                            }
                            else
                            {
                                <td class="text-center"> @item.StatusView </td>
                            }
                            <td class="text-center"><a onclick="downloadfile(@item.WorkId,@item.ResourceID)"><i class="fa fa-download"></i> </a> </td>
                            <td class="text-center"><a class="btn purple btn-outline sbold" onclick="ShowModel(@item.WorkId)" data-toggle="modal" href="#large"> <i class="fa fa-check"></i> </a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        @{Html.RenderPartial("~/Views/Shared/Pagination.cshtml");}
    </div>

    <div class="modal fade bs-modal-lg" id="large" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Đầu việc</h4>
                </div>
                @Html.HiddenFor(m => m.WorkId)
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-md-2 control-label">Đầu việc</label>
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.WorkName, new { @class = "form-control ", @disabled = "disabled" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <br />
                    <div class="form-group">
                        <label class="col-md-2 control-label">Mô tả</label>
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.Description, new { @class = "form-control ", @disabled = "disabled" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <br />
                    <div class="form-group">
                        <label class="col-md-2 control-label">Ghi chú</label>
                        <div class="col-md-6">
                            @Html.TextAreaFor(m => m.NoteByUser, new { @class = "form-control " })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <br />
                    <div class="form-group">
                        <label class="col-md-2 control-label">Công việc</label>
                        <div class="col-md-6">
                            <div class="mt-radio-inline">
                                <label class="mt-radio">
                                    <input type="radio" class="aaaa" name="optionsRadios" id="check_hoanthanh" value="option1"> Hoàn thành
                                    <span></span>
                                </label>
                                <label class="mt-radio">
                                    <input type="radio" name="optionsRadios" id="check_xuly" value="option2"> Đang xử lý
                                    <span></span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <br />
                    <div class="form-group">
                        <label class="col-md-6 control-label">Danh sách nhân viên được giao </label>
                    </div>
                    <br />
                    <div class="form-group">
                        <table class="table table-striped table-bordered table-hover table-header-fixed dataTable no-footer" id="sample_1" role="grid" aria-describedby="sample_1_info">
                            <thead>
                                <tr>
                                    <td class="">Họ và tên</td>
                                    <td class="text-center">Phòng ban</td>
                                </tr>
                            </thead>
                            <tbody class="listUser"></tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                    <br />
                </div>
                <br />
                <div class="modal-footer">
                    <button type="button" class="btn dark btn-outline" data-dismiss="modal">Đóng</button>
                    <button type="button" id="btn_Save" class="btn green">Lưu</button>
                </div>


            </div>
        </div>
    </div>

</div>
@section scripts{

    <script type="text/javascript">


        $(document).ready(function () {
            $('.nav-item').removeClass('open active');
            $('#dauviecduocgiao').addClass('open active');
        });
        function ShowModel(id) {
           // RemoveAllCheck();
            $(".remove_user").remove();
            ShowLoading();
            $.ajax({
                type: "POST",
                url: '/Work/GetWork',
                data: JSON.stringify({ 'workId': id }),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (msg) {
                    $('#WorkId').val(msg.WorkId);
                    $('#WorkName').val(msg.WorkName);
                    $('#Description').val(msg.Description);
                    $('#NoteByUser').val(msg.NoteByUser);
                    $('[name="optionsRadios"]').removeAttr('checked');
                    if (msg.Status == 3) {
                        $("input[name=optionsRadios][value='option1']").prop('checked', true);
                    }
                    else {
                        $("input[name=optionsRadios][value='option2']").prop('checked', true);
                    }
                    for (var i = 0; i < msg.lstUserWork.length; i++) {

                        if (msg.lstUserWork[i].CheckStatus == 1) {
                            $('.listUser').append("<tr class='remove_user'> \
                            <td class= ''> "+ msg.lstUserWork[i].Fullname + "</td >\
                            <td class='text-center'>"+ msg.lstUserWork[i].ResourceName + "</td></tr>");
                        }
                    }
                    StopShowLoading();
                }
            });
        }
        function RemoveAllCheck() {
            $('#check_hoanthanh').removeAttr('checked', false)
            $('#check_xuly').removeAttr('checked', false)
        }

        $(document).on('click', '#btn_Save', function () {
            var status = 0
            if ($('#check_hoanthanh').is(':checked')) {
                status = 1;
            }
            ShowLoading();
            $.ajax({
                type: "POST",
                url: '/WorkUser/UpdateStatusWork',
                data: JSON.stringify({ 'workId': $('#WorkId').val(), 'notebyuser': $('#NoteByUser').val(), 'status': status}),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data, status) {
                    if (data.Status == 1) {
                        location.reload();
                        $('#large').modal().hide();
                        toastr["success"](data.Message, "Thành công");
                    }
                    else {

                        toastr["error"](data.Message, "Lỗi");
                    }
                    StopShowLoading();

                }
            });
        });

        function downloadfile(id, resourceID) {
                $.ajax({
                    type: "POST",
                    url: '/WorkUser/ExporFile',
                    data: JSON.stringify({ 'id': id}),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                }).done(function (data) {
                    if (data.fileName != "") {
                        var url = '@Html.Raw(Url.Action("Download", "WorkUser", new { file = "__productId__", resourceID = "__orderId__"}))';
                        var params = url.replace('__productId__', data.fileName).replace('__orderId__', resourceID);
                        window.location.href = params;
                    }
                    else {
                        toastr["error"](data.errorMessage, "Lỗi ! không tìm thấy file");
                    }
                });
        }

        function page_click(CurrentPage) {
            var TotalPage =$('#hdd_TotalPage').val();
            if (CurrentPage < 1) return;
            if (CurrentPage > TotalPage) return;
             $("#PageCurrent").val(CurrentPage);
            var url = '@Html.Raw(Url.Action("Index", "WorkUser", new { CurrentPage = " __currenpage__" }))';
            var params = url.replace('__currenpage__', CurrentPage);
            window.location.href = params;
        }

    </script>
}