InformationFile/Controllers/WorkController.cs
using InformationFile.Extention;
using InformationFile.Models.User;
using InformationFile.Models.Work;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace InformationFile.Controllers
{
    public class WorkController : Controller
    {
        private TimaFMEntities db = new TimaFMEntities();
        // GET: Work
        [CheckLogin]
        public ActionResult Index(WorkModel model)
        {
            model.CurrentPage = model.CurrentPage == 0 ? 1 : model.CurrentPage;
            ViewBag.UserName = AuthenUser.CurrentUser().Fullname;

            var lstResource = db.tblResources.ToList();
            lstResource.Add(new tblResource() { ResourceID = 0, Description = "--Tất cả--" });
            model.ListResource = lstResource;
            var userid = AuthenUser.CurrentUser().UserID;

            var lstwork = db.tblWorks.Where(m => m.UserID == userid).ToList();
            var total = lstwork.Count();
            model.ListItem = lstwork.Select(m => new WorkItemModel()
            {
                WorkId = m.WorkId,
                Description = m.Description,
                WorkName = m.WorkName,
                MediaUrl = m.MediaUrl,
                Createdate = m.Createdate,
                ResourceName = db.tblResources.FirstOrDefault(n => n.ResourceID == m.ResourceID).Description,
                FromUser = db.tblUsers.FirstOrDefault(n => n.UserID == m.UserID).Fullname,
                Status = (int)m.Status
                //Url = "/DATA" + resource.FirstOrDefault(k => k.ResourceID == m.ResourceID).ResourceUrl + "/" + m.MediaUrl

            }).ToList().OrderByDescending(k => k.Createdate).Skip((model.CurrentPage - 1) * 10).Take(10).ToList();

            //model.ListItem.OrderByDescending(l =>l.Createdate).ToList();
            model.ListItem = model.ListItem;

            ViewBag.CurrentPage = model.CurrentPage;
            ViewBag.TotalPage = (int)Math.Ceiling((decimal)total / 10);

            ViewBag.ResourceName = AuthenUser.CurrentUser().ResourceName;
            return View(model);
        }
        [CheckLogin]
        [HttpPost]
        public ActionResult AddWork(string workName, string description, int resourceID)
        {
            string fname = "";
            if (Request.Files.Count > 0)
            {
                try
                {
                    //  Get all files from Request object  
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        //string path = AppDomain.CurrentDomain.BaseDirectory + "Uploads/";  
                        //string filename = Path.GetFileName(Request.Files[i].FileName);  

                        HttpPostedFileBase file = files[i];

                        var supportedTypes = new[] { "txt", "doc", "docx", "pdf", "xls", "xlsx" };
                        var fileExt = System.IO.Path.GetExtension(file.FileName).Substring(1);
                        //Checking for Internet Explorer
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            string date = DateTime.Now.ToString("dd/MM/yyyy HH:mm").Replace("/", "_").Replace(" ", "_").Replace(":", "_");

                            fname = Path.GetFileName(date + file.FileName);
                            if (fileExt.Contains("exe"))
                            {
                                return new JsonResult { Data = new { Status = 0, Message = "Lỗi .! Upload file thất bại" } };
                            }
                        }
                        IQueryable<tblResource> resource = db.tblResources;
                        var resourceUrl = resource.FirstOrDefault(k => k.ResourceID == resourceID).ResourceUrl;
                        var path = "~/Data" + resourceUrl;
                        // Get the complete folder path and store the file inside it.  
                        var newpath = Path.Combine(Server.MapPath(path), fname);
                        file.SaveAs(newpath);
                    }
                    // Returns message that successfully uploaded  

                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message);
                }
            }
            tblWork work = new tblWork();
            work.WorkName = workName;
            work.Description = description;
            work.MediaUrl = fname;
            work.Createdate = DateTime.Now;
            //work.MediaType = fileExt;
            work.ResourceID = resourceID;
            work.UserID = AuthenUser.CurrentUser().UserID;
            work.Status = (int)StatusEnum.DaGui;
            db.tblWorks.Add(work);
            db.SaveChanges();
            db.Dispose();
            int id = work.WorkId;
            if (id > 0)
            {
                return new JsonResult { Data = new { Status = 1, Message = "Tạo mới  thành công .!" } };
            }
            else
            {
                return new JsonResult { Data = new { Status = 0, Message = "Lỗi .! tạo mới  thất bại" } };
            }
        }

        [CheckLogin]
        public ActionResult ListWorkByResource(WorkModel model)
        {
            model.CurrentPage = model.CurrentPage == 0 ? 1 : model.CurrentPage;
            //WorkModel model = new WorkModel();

            var userid = AuthenUser.CurrentUser().UserID;
            var resourceID = AuthenUser.CurrentUser().ResourceID;

            var lstwork = db.tblWorks.Where(m => m.UserID == userid && m.ResourceID == resourceID).ToList().OrderByDescending(m => m.Createdate).ToList();
            foreach (var item in lstwork)
            {
                WorkItemModel workmodel = new WorkItemModel();
                workmodel.WorkId = item.WorkId;
                workmodel.Description = item.Description;
                workmodel.WorkName = item.WorkName;
                workmodel.MediaUrl = item.MediaUrl;
                workmodel.Createdate = item.Createdate;
                workmodel.Status = (int)item.Status;
                workmodel.NoteByUser = item.NoteByUser;
                workmodel.ResourceName = db.tblResources.FirstOrDefault(n => n.ResourceID == item.ResourceID).Description;
                workmodel.FromUser = db.tblUsers.FirstOrDefault(n => n.UserID == item.UserID).Fullname;

                //Url = "/DATA" + resource.FirstOrDefault(k => k.ResourceID == m.ResourceID).ResourceUrl + "/" + m.MediaUrl
                model.ListItem.Add(workmodel);
            }
            ViewBag.ResourceName = AuthenUser.CurrentUser().ResourceName;

            var total = model.ListItem.Count();
            ViewBag.CurrentPage = model.CurrentPage;
            ViewBag.TotalPage = (int)Math.Ceiling((decimal)total / 10);

            model.ListItem = model.ListItem.Skip((model.CurrentPage - 1) * 10).Take(10).ToList();

            return View(model);
        }
        [CheckLogin]
        [HttpPost]
        public JsonResult GetWork(int workId)
        {
            WorkItemModel obj = new WorkItemModel();
            IQueryable<tblRole> role = db.tblRoles;
            var resourceID = AuthenUser.CurrentUser().ResourceID;
            var objwork = db.tblWorks.FirstOrDefault(m => m.WorkId == workId);

            obj.WorkId = objwork.WorkId;
            obj.WorkName = objwork.WorkName;
            obj.Description = objwork.Description;
            obj.NoteByLeader = objwork.NoteByLeader;
            obj.NoteByUser = objwork.NoteByUser;
            obj.Status = (int)objwork.Status;

            var lstWorkUser = db.tblWorkUsers.Where(n => n.WorkId == workId).ToList();
            //lst user theo pb
            var lstUser = db.tblUsers.Where(m => m.ResourceID == resourceID).ToList();

            List<tbl_User> lstUserNew = new List<tbl_User>();
            foreach (var item in lstUser)
            {
                if (lstWorkUser.Any(p => p.ToUser == item.UserID))
                {
                    var i = new tbl_User()
                    {
                        UserID = item.UserID,
                        Fullname = item.Fullname,
                        ResourceName = db.tblResources.FirstOrDefault(m => m.ResourceID == item.ResourceID).Description,
                        CheckStatus = 1
                    };
                    lstUserNew.Add(i);
                }
                else
                {
                    var i = new tbl_User()
                    {
                        UserID = item.UserID,
                        Fullname = item.Fullname,
                        CheckStatus = 0
                    };
                    lstUserNew.Add(i);
                }
            }
            obj.lstUserWork = lstUserNew;
            db.Dispose();
            return Json(obj, JsonRequestBehavior.AllowGet);
        }
        [CheckLogin]
        public ActionResult AddWorkToUser(int workId, string toUser, string notebyleader)
        {
            try
            {
                char[] delimiters = { ' ', ',' };
                string[] petsArray = toUser.Split(delimiters);
                //xóa cac user được assigned 
                var workobj = db.tblWorkUsers.Where(m => m.WorkId == workId);
                if (workobj.Count() > 0)
                {
                    db.tblWorkUsers.RemoveRange(workobj);
                    db.SaveChanges();
                }
                //add user được assigned
                foreach (var user in petsArray)

InformationFile/Views/Resource/Index.cshtml
@model InformationFile.Models.Resource.ResourceModel
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            @*<a href="#"> @ViewBag.UserName</a>*@
            <a href="#">Tạo phòng ban</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>@ViewBag.Email</span>
        </li>
    </ul>
</div>
<br />
<div class="portlet-title">
    <div class="tools">
        <a href="javascript:;" class="collapse"> </a>
        <a href="#portlet-config" data-toggle="modal" class="config"> </a>
        <a href="javascript:;" class="reload"> </a>
        <a href="javascript:;" class="remove"> </a>
    </div>
</div>
<input type="hidden" value="1" name="PageCurrent" id="PageCurrent" />
<div class="portlet-body form">
    <!-- BEGIN FORM-->
    <div class="form-horizontal">
        <div class="form-body">
            <div class="form-group">
                <label class="col-md-3 control-label">Tên phòng ban</label>
                <div class="col-md-4">
                    @Html.TextBoxFor(m => m.Description, new { @class = "form-control", @placeholder = "Tên phòng ban" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label">URL</label>
                <div class="col-md-4">
                    @Html.TextBoxFor(m => m.ResourceUrl, new { @class = "form-control ", @placeholder = "Url" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label">Số thứ tự</label>
                <div class="col-md-4">
                    @Html.TextBoxFor(m => m.Number, new { @class = "form-control", @type = "number" , @min = "1", @max = "100" ,@placeholder = "Số thứ tự" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label"></label>
            <div class="col-md-4">
                <input type="button" id="btnAdd" name="name" value="Tạo mới" style="margin-left:10px" class="btn  green" />
            </div>
        </div>
        <hr />
        <div class="clearfix"></div>
        <table class="table table-striped table-bordered table-hover table-header-fixed dataTable no-footer" id="sample_1" role="grid" aria-describedby="sample_1_info">
            <thead>
                <tr>
                    <th> # </th>
                    <th class="text-left"> Tên Phòng ban </th>
                    <th class="text-center"> Url </th>
                    <th class="text-center"> Số thứ tự </th>
                    <th class="text-center">Sửa</th>
                    <th class="text-center">Xóa</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.ListItem != null && Model.ListItem.Count > 0)
                {
                    int indexRow = 0;
                    //if (Model.CurrentPage > 1)
                    //{
                    //    indexRow = 10 * (Model.CurrentPage - 1);
                    //}
                    foreach (var item in Model.ListItem)
                    {
                        indexRow++;
                        <tr>
                            <td> @indexRow </td>
                            <td class="text-left"> @item.Description </td>
                            <td class="text-center"> @item.ResourceUrl </td>
                            <td class="text-center"> @item.Number </td>
                            <td class="text-center"><a class="" onclick="ShowModel(@item.ResourceID)" data-toggle="modal" href="#large"><i class="fa fa-edit"></i></a></td>
                            <td class="text-center"><a class="" onclick="DeleteWorkId(@item.ResourceID)"><i class="fa fa-trash"></i></a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        @{Html.RenderPartial("~/Views/Shared/Pagination.cshtml");}
    </div>
    @*Model*@
    <div class="modal fade bs-modal-lg" id="large" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Chỉnh sửa phòng ban</h4>
                </div>
                @Html.HiddenFor(m => m.ResourceID, new { @class = "editResourceID" })
                <input type="hidden" id="ResourceID_Old" />
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Tên phòng ban</label>
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.Description, new { @class = "form-control editDescription" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <br />
                    <div class="form-group">
                        <label class="col-md-3 control-label">Số thứ tự</label>
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.Number, new { @class = "form-control editNumber" ,@type = "number", @min = "1", @max = "100", @placeholder = "Số thứ tự" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <br />
                </div>
                <br />
                <div class="modal-footer">
                    <button type="button" class="btn dark btn-outline" data-dismiss="modal">Đóng</button>
                    <button type="button" id="btn_Update" class="btn green">Lưu</button>
                </div>


            </div>
        </div>
    </div>
</div>
@section scripts{

    <script>
        $('#ResourceUrl').keypress(function (e) {
            var regex = new RegExp(/^[a-zA-Z\s]+$/);
            var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
            if (regex.test(str)) {
                return true;
            }
            else {
                e.preventDefault();
                toastr["warning"]("Bạn chưa nhập chưa đúng định dạng", "warning");
                return false;
            }
        });
        $(document).ready(function () {
            $('.nav-item').removeClass('open active');
            $('#phongban').addClass('open active');

            $('#btnAdd').click(function () {
                if ($('#Description').val() == "") {
                    toastr["warning"]("Bạn chưa nhập tên phòng ban", "warning");
                    $('#Description').focus();
                    return false;
                }
                if ($('#ResourceUrl').val() == "") {
                    toastr["warning"]("Bạn chưa nhập Url", "warning");
                    $('#ResourceUrl').focus();
                    return false;
                }
                
                ShowLoading();
                $.ajax({
                    type: "POST",
                    url: '/Resource/AddResource',
                    data: JSON.stringify({ 'Resource': $('#Description').val(), 'ResourceUrl': $('#ResourceUrl').val(), 'Number': $('#Number').val()}),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (data, status) {
                        if (data.Status == 1) {
                            setTimeout(function () {
                                window.location.reload(1);
                            }, 1000);
                            toastr["success"](data.Message, "Thành công");
                        }
                        else {
                            setTimeout(function () {
                                window.location.reload(1);
                            }, 1000);
                            toastr["error"](data.Message, "Lỗi");
                        }
                        StopShowLoading();
                    }
                });
            });
        });
        function DeleteWorkId(id) {
            bootbox.confirm("Bạn có chắc chắn muốn xóa", function (o) {
                if (o == true) {
                    ShowLoading();
                    $.ajax({
                        type: "POST",
                        url: '/Resource/DeleteResource ',
                        data: JSON.stringify({ 'ResourceID': id }),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: function (data, status) {
                            if (data.Status == 1) {
                                setTimeout(function () {
                                    window.location.reload(1);
                                }, 1000);
                                toastr["success"](data.Message, "Thành công");
                            }
                            else {
                                setTimeout(function () {
                                    window.location.reload(1);
                                }, 1000);
                                toastr["error"](data.Message, "Lỗi");
                            }
                            StopShowLoading();
                        }
                    });
                }
            })
         }

        function ShowModel(id) {
            $('.editResourceID').val(0);
            $('.editDescription').val("");
            $('.editNumber').val(0);
            ShowLoading();
            $.ajax({
                type: "POST",
                url: '/Resource/GetResourceById',
                data: JSON.stringify({ 'resourceID': id }),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (msg) {
                    StopShowLoading();
                    $('.editResourceID').val(msg.ResourceID);
                    $('.editDescription').val(msg.Description);
                    $('.editNumber').val(msg.Number);
                }
            });
        }

        $(document).on('click', '#btn_Update', function (e) {
            if ($('.editDescription').val() == "")
            {
                toastr["warning"]("Bạn chưa nhập tên phòng ban", "warning");
                $('.editDescription').focus();
                return false;
            } 
            ShowLoading();
            $.ajax({
                type: "POST",
                url: '/Resource/UpdateResource',
                data: JSON.stringify({ 'ResourceID' : $('.editResourceID').val() ,'Description': $('.editDescription').val(), 'Number': $('.editNumber').val()}),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data, status) {
                    if (data.Status == 1) {
                        setTimeout(function () {
                            window.location.reload(1);
                        }, 1000);
                        toastr["success"](data.Message, "Thành công");
                    }
                    else {
                        setTimeout(function () {
                            window.location.reload(1);
                        }, 1000);
                        toastr["error"](data.Message, "Lỗi");
                    }
                    StopShowLoading();
                }
            });
        
        });

          function page_click(CurrentPage) {
              var TotalPage = $('#hdd_TotalPage').val();
              if (CurrentPage < 1) return;
              if (CurrentPage > TotalPage) return;
          $("#PageCurrent").val(CurrentPage);

             var url = '@Html.Raw(Url.Action("Index", "Work", new { CurrentPage = " __currenpage__" }))';
            var params = url.replace('__currenpage__', CurrentPage);
                        window.location.href = params;
        }
    </script>
}