InformationFile/Models/Role/RoleItemModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InformationFile.Models.Role
{
    public class RoleItemModel
    {
        public int? RoleID { get; set; }
        public int? ResourceID { get; set; }
        public string ResourceName { get; set; }
        public int? UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> CmdInsert { get; set; }
        public Nullable<bool> CmdDelete { get; set; }
        public Nullable<bool> CmdView { get; set; }
    }
}

InformationFile/Models/Role/RoleModel.cs
using InformationFile.Models.UploadFile;
using InformationFile.Models.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InformationFile.Models.Role
{
    public class RoleModel
    {
        public RoleModel()
        {
            //ListItem = new List<tblResource>();
            ListItem = new List<tbl_User>();
        }
        public List<tbl_User> ListItem { get; set; }
        public string txtSearch { get; set; }
        public int ResourceID { get; set; }
        public int RoleID { get; set; }
        public string UserName { get; set; }
        public int UserID { get; set; }
        public string ResourceName { get; set; }
        public int CurrentPage { get; set; }
        public List<tblUser> ListUser { get; set; }
        public List<tblResource> ListResource { get; set; }
    }
}

InformationFile/Controllers/RoleController.cs
using InformationFile.Extention;
using InformationFile.Models.Role;
using InformationFile.Models.User;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InformationFile.Controllers
{
    public class RoleController : Controller
    {
        private TimaFMEntities db = new TimaFMEntities();
        // GET: Role
        [CheckLogin]
        public ActionResult Index(RoleModel model)
        {

            //RoleModel model = new RoleModel();
            IQueryable<tblResource> resource = db.tblResources;
            var lstResource = db.tblResources.OrderBy(m=>m.Number).ToList();
            lstResource.Add(new tblResource() { ResourceID = 0, Description = "--Tất cả--" });
            //model.ResourceID = 1;
            ViewBag.UserName = AuthenUser.CurrentUser().Fullname;
            var lstUser = db.tblUsers.ToList();
            if (model.txtSearch != null)
            {
                lstUser = lstUser.Where(m => m.Email.ToLower().Contains(model.txtSearch.ToLower()) || m.Fullname.ToLower().Contains(model.txtSearch.ToLower())).ToList();
            }

            if (model.ResourceID == 0)
            {

                List<tbl_User> lstuser = new List<tbl_User>();

                foreach (var item in lstUser)
                {
                    tbl_User user = new tbl_User();
                    user.UserID = item.UserID;
                    user.Fullname = item.Fullname;
                    user.Email = item.Email;
                    user.ResourceID = 0;
                    lstuser.Add(user);
                }
                model.ListItem = lstuser;

            }
            else
            {

                var query = (from rl in db.tblRoles
                             join us in db.tblUsers on rl.UserID equals us.UserID
                             where rl.ResourceID == model.ResourceID
                             select new { ResourceID = rl.ResourceID, UserID = us.UserID, Fullname = us.Fullname, Email = us.Email, CmdView = rl.CmdView, CmdInsert = rl.CmdInsert, CmdDelete = rl.CmdDelete , CmdEdit = rl.CmdEdit }).ToList();
                List<tbl_User> lstuser = new List<tbl_User>();

                foreach (var i in lstUser)
                {
                    //if (query.Any(p => p.UserID.Contains(i.UserID)))
                    if (query.Any(p => p.UserID == i.UserID))
                    {
                        var role = query.Where(p => p.UserID == i.UserID).FirstOrDefault();
                        var item = new tbl_User()
                        {
                            UserID = role.UserID,
                            Email = role.Email,
                            Fullname = i.Fullname,
                            ResourceID = model.ResourceID,
                            CmdView = role.CmdView,
                            CmdDelete = role.CmdDelete,
                            CmdInsert = role.CmdInsert,
                            CmdEdit = role.CmdEdit

                        };
                        lstuser.Add(item);
                    }
                    else
                    {
                        var item = new tbl_User()
                        {
                            UserID = i.UserID,
                            Email = i.Email,
                            Fullname = i.Fullname,
                            ResourceID = model.ResourceID,
                            CmdView = false,
                            CmdDelete = false,
                            CmdInsert = false,
                            CmdEdit = false

                        };
                        lstuser.Add(item);
                    }
                }
                model.ListItem = lstuser;
                //end else
            }
            //var a = 2;
            var count = model.ListItem.Count();
            model.ListItem = model.ListItem.Skip((model.CurrentPage - 1) * 10).Take(10).ToList();
            model.ResourceID = model.ResourceID;
            model.ListResource = lstResource;
            db.Dispose();
            ViewBag.CurrentPage = model.CurrentPage;
            ViewBag.TotalPage = (int)Math.Ceiling((decimal)count / 10);
            model.txtSearch = model.txtSearch;
            return View(model);
        }
        [HttpPost]
        public JsonResult GetResource(int resourceID)
        {
            RoleItemModel obj = new RoleItemModel();
            IQueryable<tblRole> role = db.tblRoles;
            var userid = AuthenUser.CurrentUser().UserID;
            var objRole = role.FirstOrDefault(m => m.ResourceID == resourceID);
            obj.ResourceName = db.tblResources.FirstOrDefault(n => n.ResourceID == resourceID).Description;
            obj.RoleID = objRole.RoleID;
            obj.ResourceID = objRole.ResourceID;
            //obj.CmdInsert = objRole.CmdInsert;
            //obj.CmdView = objRole.CmdView;
            //obj.CmdDelete = objRole.CmdDelete;

            //obj.UserID = objRole.UserID;
            db.Dispose();

            return Json(obj, JsonRequestBehavior.AllowGet);
        }
        [CheckLogin]
        public ActionResult UpdateRole(int userid, int resourceid, bool role, int type)
        {

            IQueryable<tblRole> tblrole = db.tblRoles;
            var ObjRole = tblrole.FirstOrDefault(m => m.ResourceID == resourceid && m.UserID == userid);
            tblRole obj = new tblRole();

            if (ObjRole != null)
            {
                //update
                // type=1 = view , type=2=insert ,type =3=delete ,type= 4= edit
                if (type == 1)
                {
                    obj = db.tblRoles.Find(ObjRole.RoleID);
                    db.Entry(obj).State = EntityState.Modified;
                    obj.UserID = userid;
                    obj.ResourceID = resourceid;
                    obj.CmdView = role;
                    db.SaveChanges();
                }
                if (type == 2)
                {
                    obj = db.tblRoles.Find(ObjRole.RoleID);
                    db.Entry(obj).State = EntityState.Modified;
                    obj.UserID = userid;
                    obj.ResourceID = resourceid;
                    obj.CmdInsert = role;
                    db.SaveChanges();
                }
                if (type == 3)
                {
                    obj = db.tblRoles.Find(ObjRole.RoleID);
                    db.Entry(obj).State = EntityState.Modified;
                    obj.UserID = userid;
                    obj.ResourceID = resourceid;
                    obj.CmdDelete = role;
                    db.SaveChanges();
                }
                if (type == 4)
                {
                    obj = db.tblRoles.Find(ObjRole.RoleID);
                    db.Entry(obj).State = EntityState.Modified;
                    obj.UserID = userid;
                    obj.ResourceID = resourceid;
                    obj.CmdEdit = role;
                    db.SaveChanges();
                }
                int id = obj.RoleID;
                db.Dispose();
                if (id > 0)
                {
                    return new JsonResult { Data = new { Status = 1, Message = "Update thành công .!" } };
                }
                else
                {
                    return new JsonResult { Data = new { Status = 1, Message = "Lỗi .! Update thất bại" } };
                }
            }
            else
            {
                //insert
                if (type == 1)
                {
                    obj.UserID = userid;
                    obj.ResourceID = resourceid;
                    obj.CmdView = role;
                    db.tblRoles.Add(obj);
                    db.SaveChanges();
                }
                if (type == 2)
                {
                    obj.UserID = userid;
                    obj.ResourceID = resourceid;
                    obj.CmdInsert = role;
                    db.tblRoles.Add(obj);
                    db.SaveChanges();
                }
                if (type == 3)
                {
                    obj.UserID = userid;
                    obj.ResourceID = resourceid;
                    obj.CmdDelete = role;
                    db.tblRoles.Add(obj);
                    db.SaveChanges();
                }
                int id = obj.RoleID;
                db.Dispose();
                if (id > 0)
                {
                    return new JsonResult { Data = new { Status = 1, Message = "Update thành công .!" } };
                }
                else
                {
                    return new JsonResult { Data = new { Status = 1, Message = "Lỗi .! Update thất bại" } };
                }

            }

            return new JsonResult { Data = new { Status = 0, Message = "" } };
        }
        [CheckLogin]
        public ActionResult GetRoleUser(int userID, int resourceId)
        {
            IQueryable<tblRole> role = db.tblRoles;
            var obj = role.FirstOrDefault(m => m.UserID == userID && m.ResourceID == resourceId);
            return Json(obj, JsonRequestBehavior.AllowGet);
        }

    }
}

InformationFile/Views/Role/Index.cshtml
@model InformationFile.Models.Role.RoleModel

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="index.html"> Phân quyền</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>@ViewBag.UserName</span>
        </li>
    </ul>
</div>
<br />
<div class="portlet-body form">
    <form class="form-vertical" action="/Role/Index" method="post" id="formRole">
        <div class="portlet-body">
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-1 control-label" style="margin-right:-50px">Phòng ban</label>
                    <div class="col-md-2">
                        @Html.DropDownListFor(model => model.ResourceID, new SelectList(Model.ListResource, "ResourceID", "Description"), new { @class = "form-control " })
                    </div>
                    <label class="col-md-1 control-label" style="margin-right:-50px">Họ và tên</label>
                    <div class="col-md-2">
                        @Html.TextBoxFor(m => m.txtSearch, new { @class = "form-control ", @placeholder = "Họ và tên ,Email" })
                    </div>
                    <div class="col-md-1">
                        <input type="submit" value="Tìm kiếm" class="btn btn-primary" />
                    </div>
                </div>


            </div>
            <br />
            <table class="table table-striped table-checkable table-bordered table-hover" id="sample_1">
                <thead>
                    <tr>
                        <th> # </th>
                        <th> Email</th>
                        <th> Họ tên</th>
                        <th class="text-center">Xem </th>
                        <th class="text-center">Upload</th>
                        <th class="text-center">Edit</th>
                        <th class="text-center">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.ListItem != null && Model.ListItem.Count > 0)
                    {
                        int indexRow = 0;
                        if (Model.CurrentPage > 1)
                        {
                            indexRow = 10 * (Model.CurrentPage - 1);

                        }

                        foreach (var item in Model.ListItem)
                        {
                            indexRow++;
                            <tr>
                                <td> @indexRow </td>
                                <td> @item.Email </td>
                                <td> @item.Fullname </td>
                                <td class="text-center">
                                    @if (item.CmdView == true)
                                    {
                                        <input type="checkbox" id="cb_View_@item.UserID" class="cb_View" value="0" checked onclick="SaveCB_View(@item.UserID,@item.ResourceID)">
                                    }
                                    else
                                    {
                                        <input type="checkbox" id="cb_View_@item.UserID" class="cb_View" onclick="SaveCB_View(@item.UserID,@item.ResourceID)">
                                    }
                                </td>
                                <td class="text-center">
                                    @if (item.CmdInsert == true)
                                    {
                                        <input type="checkbox" id="cb_Upload_@item.UserID" class="cb_Upload" checked onclick="SaveCB_Insert(@item.UserID,@item.ResourceID)">
                                    }
                                    else
                                    {
                                        <input type="checkbox" id="cb_Upload_@item.UserID" class=" cb_Upload" onclick="SaveCB_Insert(@item.UserID,@item.ResourceID)">
                                    }
                                </td>
                                <td class="text-center">
                                    @if (item.CmdEdit == true)
                                    {
                                        <input type="checkbox" id="cb_Edit_@item.UserID" class="cb_Edit" checked onclick="SaveCB_Edit(@item.UserID,@item.ResourceID)">
                                    }
                                    else
                                    {
                                        <input type="checkbox" id="cb_Edit_@item.UserID" class="cb_Edit" onclick="SaveCB_Edit(@item.UserID,@item.ResourceID)">
                                    }

                                </td>
                                <td class="text-center">
                                    @if (item.CmdDelete == true)
                                    {
                                        <input type="checkbox" id="cb_Delete_@item.UserID" class="cb_Delete" checked onclick="SaveCB_Delete(@item.UserID,@item.ResourceID)">
                                    }
                                    else
                                    {
                                        <input type="checkbox" id="cb_Delete_@item.UserID" class="cb_Delete" onclick="SaveCB_Delete(@item.UserID,@item.ResourceID)">
                                    }

                                </td>
                                <td hidden class="info_user" data-id="@item.UserID"></td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            @{Html.RenderPartial("~/Views/Shared/Pagination.cshtml");}
        </div>
    </form>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('.nav-item').removeClass('open active');
            $('#phanquyen').addClass('open active');
        });
        $(document).on('change', '#ResourceID', function () {
            @*var url = '@Html.Raw(Url.Action("Index", "Role", new { ResourceID = "__productId__"}))';
            var params = url.replace('__productId__', $(this).val());
                        window.location.href = params;*@
            $('#formRole').submit();
        })

        function page_click(CurrentPage) {
            if (CurrentPage < 1) return;
          $("#PageCurrent").val(CurrentPage);

            var url = '@Html.Raw(Url.Action("Index", "Role", new { ResourceID = "__productId__",CurrentPage = " __currenpage__" }))';
            var params = url.replace('__productId__', $('#ResourceID').val()).replace('__currenpage__', CurrentPage);
                        window.location.href = params;

        }

        var cb_View = false;
        var cb_Insert = false;
        var cb_Edit = false;
        var cb_Delete = false;
        var arr = [];

        function SaveCB_View(userID, resourceId) {
            if (resourceId == 0) {
                toastr["warning"]("Bạn chưa chọn phòng ban", "Lỗi");
                return false;
            }
            debugger
            if ($("#cb_View_" + userID).prop('checked')) {
                cb_View = true;
            }
            ShowLoading();
            $.ajax({
                type: "POST",
                url: '/Role/UpdateRole',
                data: JSON.stringify({ 'userid': userID, 'resourceid': resourceId, 'role': cb_View,'type' : 1 }),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data, status) {
                    if (data.Status == 1) {
                        toastr["success"](data.Message, "Thành công");
                    }
                    else {

                        toastr["error"](data.Message, "Lỗi");
                    }
                    StopShowLoading();
                }
            });
        }
        function SaveCB_Insert(userID, resourceId) {
            if (resourceId == 0) {
                toastr["warning"]("Bạn chưa chọn phòng ban", "Lỗi");
                return false;
            }
            if ($("#cb_Upload_" + userID).prop('checked')) {
                cb_Insert = true;
            }
             ShowLoading();
            $.ajax({
                type: "POST",
                url: '/Role/UpdateRole',
                data: JSON.stringify({ 'userid': userID, 'resourceid': resourceId, 'role': cb_Insert, 'type': 2 }),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data, status) {
                    if (data.Status == 1) {
                        toastr["success"](data.Message, "Thành công");
                    }
                    else {

                        toastr["error"](data.Message, "Lỗi");
                    }
                    StopShowLoading();
                }
            });
        }

        function SaveCB_Edit(userID, resourceId) {
            if (resourceId == 0) {
                toastr["warning"]("Bạn chưa chọn phòng ban", "Lỗi");
                return false;
            }
            debugger
            if ($("#cb_Edit_" + userID).prop('checked')) {
                cb_Edit = true;
            }
            ShowLoading();
            $.ajax({
                type: "POST",
                url: '/Role/UpdateRole',
                data: JSON.stringify({ 'userid': userID, 'resourceid': resourceId, 'role': cb_Edit, 'type': 4 }),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data, status) {
                    if (data.Status == 1) {
                        toastr["success"](data.Message, "Thành công");
                    }
                    else {

                        toastr["error"](data.Message, "Lỗi");
                    }
                    StopShowLoading();
                }
            });
        }
        function SaveCB_Delete(userID, resourceId) {
            if (resourceId == 0) {
                toastr["warning"]("Bạn chưa chọn phòng ban", "Lỗi");
                return false;
            }
            if ($("#cb_Delete_" + userID).prop('checked')) {
                cb_Delete = true;
            }
            ShowLoading();
            $.ajax({
                type: "POST",
                url: '/Role/UpdateRole',
                data: JSON.stringify({ 'userid': userID, 'resourceid': resourceId, 'role': cb_Delete, 'type': 3 }),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data, status) {
                    if (data.Status == 1) {
                        toastr["success"](data.Message, "Thành công");
                    }
                    else {

                        toastr["error"](data.Message, "Lỗi");
                    }
                    StopShowLoading();
                }
            });
        }
    </script>
}